AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM role for AWS Marketplace AMI with minimal privileges'

Parameters:
  SecretName:
    Type: String
    Default: 'marketplace-license-key'
    Description: 'Name of the secret containing license information'

Resources:
  MarketplaceInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretName}*'
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/marketplace/*'

  MarketplaceInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref MarketplaceInstanceRole

Outputs:
  InstanceProfileArn:
    Description: 'ARN of the instance profile for marketplace AMI'
    Value: !GetAtt MarketplaceInstanceProfile.Arn
    Export:
      Name: !Sub '${AWS::StackName}-InstanceProfile'
